version: '3.7'

services:
    app:
        build: .
        container_name: rbi-auth-app
        entrypoint: .docker/entrypoint.sh
        environment:
            NODE_ENV: dev
            PORT: 5000
        depends_on:
            - mongodb
            - redis
        links:
            - mongodb
            - redis
        ports:
            - 5000:5000
        volumes:
            - .:/home/node/app

    mongodb:
        container_name: rbi-auth-mongo
        image: bitnami/mongodb:latest
        ports:
            - 27016:27017
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - MONGODB_PORT_NUMBER=27016
        volumes:
            - mongodb_data:/bitnami/mongodb/database

    redis:
        container_name: rbi-auth-redis
        image: bitnami/redis:latest
        ports:
            - 7000:7000
        environment:
            - REDIS_PASSWORD="password"
            - REDIS_PORT_NUMBER=7000
        volumes:
            - redis_data:/bitnami/redis/database

volumes:
    redis_data:
    mongodb_data:
