version: "3.7"

services:
  app:
    build: .
    container_name: "rbi-auth"
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
      - redis
    command: yarn dev
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      NODE_ENV: dev
      PORT: 5000

  mongodb:
    container_name: "mongo-auth"
    image: bitnami/mongodb:latest
    ports:
      - 27016:27016
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_PORT_NUMBER=27016
    volumes:
      - "mongodb_data:/bitnami/mongodb/database"

  redis:
    container_name: "redis-auth"
    image: bitnami/redis:latest
    ports:
      - 7000:7000
    environment:
      REDIS_PASSWORD: "password"
    volumes:
      - redis_data:/bitnami/redis/database

volumes:
  mongodb_data:
  redis_data:
